language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: heroku
  skip_cleanup: true
  app: medvind-frontend
  local_dir: build
  api_key:
      secure: "$HEROKU_API_KEY"
  on:
    repo: KrokusMorning/medvind-frontend
    